#!/usr/bin/env bash
# core — system CLI tools, build toolchain, shell utilities, base directory
# layout, and the two-line PATH setup. Everything here is global (apt) and
# broadly useful across every project. Sourced by bootstrap.sh; defines
# functions only.

core_desc() { echo "apt CLI tools, build toolchain, shell utils, folders + PATH"; }

core_install() {
    core_layout
    core_packages
    core_binary_aliases
    core_link_repo_bins
    core_write_shellrc
    core_record_manifest
}

# Link the repo's bin/ scripts (devtools, …) into ~/tools/bin so they're on
# PATH. Symlinks point back at the repo, so a `git pull` updates them in place.
core_link_repo_bins() {
    local f name
    for f in "$REPO_ROOT"/bin/*; do
        [ -f "$f" ] || continue
        name="$(basename "$f")"
        ln -sf "$f" "$HOME/tools/bin/$name"
        log_ok "linked $name -> repo bin/"
    done
}

# Base home-directory layout the rest of the environment assumes.
core_layout() {
    ensure_dir "$HOME/projects"
    ensure_dir "$HOME/sandboxes"
    ensure_dir "$HOME/tools/bin"
    ensure_dir "$HOME/tools/logs"
    ensure_dir "$HOME/.local/bin"
}

# All in Debian trixie apt — one call, idempotent.
core_packages() {
    apt_install \
        git curl wget unzip zip tar ca-certificates gnupg \
        build-essential pkg-config make cmake ninja-build \
        gcc g++ clang gdb lldb valgrind strace \
        ripgrep fd-find fzf bat git-delta jq yq tree sqlite3 \
        tmux entr socat htop btop shellcheck shfmt tokei \
        gh hyperfine time \
        sshpass expect
}

# Debian ships fd as `fdfind` and bat as `batcat` (name conflicts). Expose the
# conventional names from ~/tools/bin without colliding with the real packages.
core_binary_aliases() {
    if has fdfind && [ ! -e "$HOME/tools/bin/fd" ]; then
        ln -sf "$(command -v fdfind)" "$HOME/tools/bin/fd"; log_ok "linked fd -> fdfind"
    fi
    if has batcat && [ ! -e "$HOME/tools/bin/bat" ]; then
        ln -sf "$(command -v batcat)" "$HOME/tools/bin/bat"; log_ok "linked bat -> batcat"
    fi
}

# Generated shell config lives in its own file, fully rewritten each run. The
# only edit to ~/.bashrc is a single idempotent sourcing line (see ensure_line).
# This is how we keep exactly two PATH additions and avoid a fragile mega-PATH.
core_write_shellrc() {
    local rc="$HOME/tools/shellrc.sh"
    cat > "$rc" <<'SH'
# Generated by wsl-dev-envbuild bootstrap — do NOT edit; regenerated on re-run.
# The only two base PATH additions: pipx shims and our user tool scripts.
case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) export PATH="$HOME/.local/bin:$PATH";; esac
case ":$PATH:" in *":$HOME/tools/bin:"*)   ;; *) export PATH="$HOME/tools/bin:$PATH";;   esac
SH
    log_ok "wrote $rc"
    # shellcheck disable=SC2016  # literal $HOME is intentional — it expands at shell-init, not here
    ensure_line "$HOME/.bashrc" '[ -f "$HOME/tools/shellrc.sh" ] && . "$HOME/tools/shellrc.sh"'
}

# Record everything this module installed into the agent-discoverable manifest.
core_record_manifest() {
    local pairs=(
        "git:git" "curl:curl" "wget:wget" "unzip:unzip" "zip:zip" "tar:tar"
        "make:make" "cmake:cmake" "ninja-build:ninja" "gcc:gcc" "g++:g++"
        "clang:clang" "gdb:gdb" "lldb:lldb" "valgrind:valgrind" "strace:strace"
        "ripgrep:rg" "fd-find:fdfind" "fzf:fzf" "bat:batcat" "git-delta:delta"
        "jq:jq" "yq:yq" "tree:tree" "sqlite3:sqlite3" "tmux:tmux" "entr:entr"
        "socat:socat" "htop:htop" "btop:btop" "shellcheck:shellcheck"
        "shfmt:shfmt" "tokei:tokei" "gh:gh" "hyperfine:hyperfine"
    )
    local pair name bin detect
    for pair in "${pairs[@]}"; do
        name="${pair%%:*}"; bin="${pair##*:}"
        has "$bin" || continue
        # Most tools answer `--version`; a few use a different flag or none.
        case "$bin" in
            unzip)        detect="unzip -v" ;;
            tmux|socat)   detect="$bin -V" ;;
            entr)         detect="command -v entr" ;;
            gh)           detect="gh --version" ;;
            *)            detect="$bin --version" ;;
        esac
        manifest_add "$name" "$bin" "core" "global" "apt" "$detect" "core" ""
    done
    if has sshpass; then manifest_add sshpass sshpass core global apt "sshpass -V" core "non-interactive SSH password auth"; fi
    if has expect;  then manifest_add expect  expect  core global apt "expect -version"    core "scripted interactive CLI automation"; fi
    # GNU time — /usr/bin/time (separate from the shell builtin `time`).
    if [ -x /usr/bin/time ]; then
        manifest_add gnu-time time core global apt "/usr/bin/time --version" core "GNU time — resource usage + CPU stats; invoke as /usr/bin/time (not shell builtin)"
    fi
    log_ok "manifest updated — $MANIFEST"
}
