#!/usr/bin/env bash
# reverse — reverse-engineering and binary-analysis toolkit (WSL-native, CLI).
#
# Most tools come from apt. radare2 isn't in trixie apt, so it's pulled as the
# official .deb from GitHub. Ghidra is a Java app downloaded from the NSA's
# GitHub releases into ~/tools/ghidra (needs the JDK from the languages group).
# frida is a Python tool via pipx. DOSBox-X is installed from apt and driven
# HEADLESS (no window) for scripted DOS-era binary analysis — the module drops
# a wrapper + config for that. See docs/architecture.md §10.
#
# GUI-heavy tools (Ghidra GUI, ImHex, Wireshark GUI) are documented as
# Windows-native-preferred; here we install the CLI/headless paths.

reverse_desc() { echo "radare2, binwalk, exiftool, tshark, foremost, headless dosbox-x, frida, Ghidra"; }

reverse_install() {
    reverse_apt
    reverse_radare2
    reverse_frida
    reverse_dosbox_headless
    reverse_ghidra
    reverse_record_manifest
}

# Everything available directly in Debian trixie.
reverse_apt() {
    apt_install \
        binwalk libimage-exiftool-perl tshark p7zip-full foremost \
        dosbox-x xxd bsdextrautils file
}

# radare2 — not in trixie apt; install the official amd64 .deb from GitHub.
# Pinned to a known-good release. Bump RADARE2_VERSION + SHA256 together after
# testing, then update source_repo entry for devtools outdated checks.
RADARE2_VERSION="6.1.6"
RADARE2_SHA256=""  # set to sha256sum of the .deb after verifying

reverse_radare2() {
    if has r2; then
        log_skip "radare2 already installed ($(r2 -v 2>/dev/null | head -1))"
        return 0
    fi
    if is_dry_run; then log_info "[DRY-RUN] would download radare2 $RADARE2_VERSION"; return 0; fi
    local url="https://github.com/radareorg/radare2/releases/download/${RADARE2_VERSION}/radare2_${RADARE2_VERSION}_amd64.deb"
    local deb; deb="$(mktemp --suffix=.deb)"
    log_info "downloading radare2 $RADARE2_VERSION"
    if curl -fsSL "$url" -o "$deb"; then
        verify_sha256 "$deb" "$RADARE2_SHA256" || { rm -f "$deb"; return 1; }
        sudo dpkg -i "$deb" >/dev/null 2>&1 || sudo apt-get install -f -y
    else
        log_warn "radare2 download failed — skipping"
    fi
    rm -f "$deb"
}

# frida dynamic-instrumentation toolkit (frida, frida-ps, frida-trace, …).
reverse_frida() { pipx_install frida-tools; }

# Headless DOSBox-X: a wrapper that forces the SDL dummy video driver (no
# window) plus a minimal default config, for scripted/automated analysis.
reverse_dosbox_headless() {
    has dosbox-x || { log_warn "dosbox-x not installed — skipping headless wrapper"; return 0; }
    ensure_dir "$HOME/tools/etc"
    local conf="$HOME/tools/etc/dosbox-x-headless.conf"
    cat > "$conf" <<'CONF'
# Generated by ai-dev-envbuild — minimal headless DOSBox-X profile.
[sdl]
output=surface
autolock=false
waitonerror=false
[dosbox]
title=headless
[autoexec]
CONF
    local wrap="$HOME/tools/bin/dosbox-x-headless"
    cat > "$wrap" <<'WRAP'
#!/usr/bin/env bash
# Headless DOSBox-X for scripted DOS-era binary analysis — no window.
# Forces the SDL dummy video driver. Uses the generated default config unless
# the caller passes its own -conf. Example:
#   dosbox-x-headless -c "MOUNT C /work" -c "C:" -c "PROG.EXE" -exit
conf="$HOME/tools/etc/dosbox-x-headless.conf"
args=("$@")
case " $* " in *" -conf "*) : ;; *) [ -f "$conf" ] && args=(-conf "$conf" "$@") ;; esac
exec env SDL_VIDEODRIVER=dummy dosbox-x "${args[@]}"
WRAP
    chmod +x "$wrap"
    log_ok "headless dosbox-x wrapper -> $wrap"
}

# Ghidra — Java RE suite from the NSA GitHub releases. Extracts to
# ~/tools/ghidra/<release> and links `ghidra` (GUI launcher) and
# `ghidra-headless` (analyzeHeadless) into ~/tools/bin.
# Pinned to a known-good release. Bump GHIDRA_VERSION + GHIDRA_ZIP + SHA256
# together after testing; verify the tag name at the GitHub releases page.
GHIDRA_VERSION="12.1"
GHIDRA_TAG="Ghidra_12.1_build"
GHIDRA_ZIP="ghidra_12.1_PUBLIC_20260513.zip"
GHIDRA_SHA256=""  # set to sha256sum of the zip after verifying

reverse_ghidra() {
    if [ -e "$HOME/tools/bin/ghidra" ]; then
        log_skip "ghidra already installed"
        return 0
    fi
    if ! has java; then
        log_warn "ghidra needs a JDK (run the languages group first) — skipping"
        return 0
    fi
    if is_dry_run; then log_info "[DRY-RUN] would download Ghidra $GHIDRA_VERSION (~400MB)"; return 0; fi
    local url="https://github.com/NationalSecurityAgency/ghidra/releases/download/${GHIDRA_TAG}/${GHIDRA_ZIP}"
    local zip; zip="$(mktemp --suffix=.zip)"
    log_info "downloading Ghidra $GHIDRA_VERSION ($GHIDRA_ZIP) — large, ~400MB"
    if ! curl -fsSL "$url" -o "$zip"; then
        log_warn "ghidra download failed — skipping"; rm -f "$zip"; return 0
    fi
    verify_sha256 "$zip" "$GHIDRA_SHA256" || { rm -f "$zip"; return 1; }
    ensure_dir "$HOME/tools/ghidra"
    unzip -q -o "$zip" -d "$HOME/tools/ghidra"
    rm -f "$zip"
    local dir
    dir="$(find "$HOME/tools/ghidra" -maxdepth 1 -type d -name 'ghidra_*_PUBLIC' | sort | tail -1)"
    if [ -z "$dir" ]; then
        log_warn "ghidra: unexpected archive layout — skipping symlinks"; return 0
    fi
    ln -sf "$dir/ghidraRun" "$HOME/tools/bin/ghidra"
    ln -sf "$dir/support/analyzeHeadless" "$HOME/tools/bin/ghidra-headless"
    log_ok "Ghidra -> $(basename "$dir") (ghidra, ghidra-headless on PATH)"
}

reverse_record_manifest() {
    if has r2;       then manifest_add radare2  r2       reverse global github-deb "r2 -v"           core "RE framework (official .deb)" "" "radareorg/radare2"; fi
    if has binwalk;  then manifest_add binwalk  binwalk  reverse global apt        "command -v binwalk"  core "firmware/binary extraction"; fi
    if has exiftool; then manifest_add exiftool exiftool reverse global apt        "exiftool -ver"    core "metadata inspection"; fi
    if has tshark;   then manifest_add tshark   tshark   reverse global apt        "tshark --version" core "CLI packet analysis (Wireshark GUI: Windows)"; fi
    if has 7z;       then manifest_add p7zip    7z       reverse global apt        "command -v 7z"       core "archive inspection/extraction"; fi
    if has foremost; then manifest_add foremost foremost reverse global apt        "command -v foremost" core "file carving from raw data"; fi
    if has xxd;      then manifest_add xxd      xxd      reverse global apt        "command -v xxd"      core "hex viewer/editor"; fi
    if has hexdump;  then manifest_add hexdump  hexdump  reverse global apt        "command -v hexdump"  core "hex dump (bsdextrautils)"; fi
    if has file;     then manifest_add file     file     reverse global apt        "file --version"   core "file-type identification"; fi
    if has dosbox-x; then manifest_add dosbox-x dosbox-x reverse global apt        "command -v dosbox-x" core "DOS emulator; run headless via dosbox-x-headless"; fi
    if has frida;    then manifest_add frida    frida    reverse global pipx       "frida --version"  core "dynamic instrumentation"; fi
    if [ -e "$HOME/tools/bin/ghidra" ]; then manifest_add ghidra ghidra reverse global github-zip "command -v ghidra" core "NSA RE suite; GUI via 'ghidra', headless via 'ghidra-headless'" "" "NationalSecurityAgency/ghidra"; fi
    log_ok "manifest updated — reverse group"
}
