#!/usr/bin/env bash
# reverse — reverse-engineering and binary-analysis toolkit (WSL-native, CLI).
#
# Most tools come from apt. radare2 isn't in trixie apt, so it's pulled as the
# official .deb from GitHub. Ghidra is a Java app downloaded from the NSA's
# GitHub releases into ~/tools/ghidra (needs the JDK from the languages group).
# frida is a Python tool via pipx. DOSBox-X is installed from apt and driven
# HEADLESS (no window) for scripted DOS-era binary analysis — the module drops
# a wrapper + config for that. See docs/architecture.md §10.
#
# GUI-heavy tools (Ghidra GUI, ImHex, Wireshark GUI) are documented as
# Windows-native-preferred; here we install the CLI/headless paths.

reverse_desc() { echo "radare2, binwalk, exiftool, tshark, foremost, headless dosbox-x, frida, Ghidra"; }

reverse_install() {
    reverse_apt
    reverse_radare2
    reverse_frida
    reverse_dosbox_headless
    reverse_ghidra
    reverse_record_manifest
}

# Everything available directly in Debian trixie.
reverse_apt() {
    apt_install \
        binwalk libimage-exiftool-perl tshark p7zip-full foremost \
        dosbox-x xxd bsdextrautils file
}

# radare2 — not in trixie apt; install the official amd64 .deb from GitHub.
reverse_radare2() {
    if has r2; then
        log_skip "radare2 already installed ($(r2 -v 2>/dev/null | head -1))"
        return 0
    fi
    local url deb
    url="$(curl -fsSL https://api.github.com/repos/radareorg/radare2/releases/latest 2>/dev/null \
        | jq -r '.assets[] | select(.name|test("^radare2_[0-9].*_amd64\\.deb$")) | .browser_download_url' | head -1)"
    if [ -z "$url" ]; then
        log_warn "radare2: could not resolve .deb URL — skipping (alt: git clone radare2 && sys/install.sh)"
        return 0
    fi
    deb="$(mktemp --suffix=.deb)"
    log_info "downloading radare2 ($(basename "$url"))"
    if curl -fsSL "$url" -o "$deb"; then
        sudo dpkg -i "$deb" >/dev/null 2>&1 || sudo apt-get install -f -y
    else
        log_warn "radare2 download failed — skipping"
    fi
    rm -f "$deb"
}

# frida dynamic-instrumentation toolkit (frida, frida-ps, frida-trace, …).
reverse_frida() { pipx_install frida-tools; }

# Headless DOSBox-X: a wrapper that forces the SDL dummy video driver (no
# window) plus a minimal default config, for scripted/automated analysis.
reverse_dosbox_headless() {
    has dosbox-x || { log_warn "dosbox-x not installed — skipping headless wrapper"; return 0; }
    ensure_dir "$HOME/tools/etc"
    local conf="$HOME/tools/etc/dosbox-x-headless.conf"
    cat > "$conf" <<'CONF'
# Generated by wsl-dev-envbuild — minimal headless DOSBox-X profile.
[sdl]
output=surface
autolock=false
waitonerror=false
[dosbox]
title=headless
[autoexec]
CONF
    local wrap="$HOME/tools/bin/dosbox-x-headless"
    cat > "$wrap" <<'WRAP'
#!/usr/bin/env bash
# Headless DOSBox-X for scripted DOS-era binary analysis — no window.
# Forces the SDL dummy video driver. Uses the generated default config unless
# the caller passes its own -conf. Example:
#   dosbox-x-headless -c "MOUNT C /work" -c "C:" -c "PROG.EXE" -exit
conf="$HOME/tools/etc/dosbox-x-headless.conf"
args=("$@")
case " $* " in *" -conf "*) : ;; *) [ -f "$conf" ] && args=(-conf "$conf" "$@") ;; esac
exec env SDL_VIDEODRIVER=dummy dosbox-x "${args[@]}"
WRAP
    chmod +x "$wrap"
    log_ok "headless dosbox-x wrapper -> $wrap"
}

# Ghidra — Java RE suite from the NSA GitHub releases. Extracts to
# ~/tools/ghidra/<release> and links `ghidra` (GUI launcher) and
# `ghidra-headless` (analyzeHeadless) into ~/tools/bin.
reverse_ghidra() {
    if [ -e "$HOME/tools/bin/ghidra" ]; then
        log_skip "ghidra already installed"
        return 0
    fi
    if ! has java; then
        log_warn "ghidra needs a JDK (run the languages group first) — skipping"
        return 0
    fi
    local url
    url="$(curl -fsSL https://api.github.com/repos/NationalSecurityAgency/ghidra/releases/latest 2>/dev/null \
        | jq -r '.assets[] | select(.name|test("PUBLIC.*\\.zip$")) | .browser_download_url' | head -1)"
    if [ -z "$url" ]; then
        log_warn "ghidra: could not resolve release URL — skipping"
        return 0
    fi
    local zip; zip="$(mktemp --suffix=.zip)"
    log_info "downloading Ghidra ($(basename "$url")) — large, ~400MB"
    if ! curl -fsSL "$url" -o "$zip"; then
        log_warn "ghidra download failed — skipping"; rm -f "$zip"; return 0
    fi
    ensure_dir "$HOME/tools/ghidra"
    unzip -q -o "$zip" -d "$HOME/tools/ghidra"
    rm -f "$zip"
    local dir
    dir="$(find "$HOME/tools/ghidra" -maxdepth 1 -type d -name 'ghidra_*_PUBLIC' | sort | tail -1)"
    if [ -z "$dir" ]; then
        log_warn "ghidra: unexpected archive layout — skipping symlinks"; return 0
    fi
    ln -sf "$dir/ghidraRun" "$HOME/tools/bin/ghidra"
    ln -sf "$dir/support/analyzeHeadless" "$HOME/tools/bin/ghidra-headless"
    log_ok "Ghidra -> $(basename "$dir") (ghidra, ghidra-headless on PATH)"
}

reverse_record_manifest() {
    if has r2;       then manifest_add radare2  r2       reverse global github-deb "r2 -v"           core "RE framework (official .deb)"; fi
    if has binwalk;  then manifest_add binwalk  binwalk  reverse global apt        "command -v binwalk"  core "firmware/binary extraction"; fi
    if has exiftool; then manifest_add exiftool exiftool reverse global apt        "exiftool -ver"    core "metadata inspection"; fi
    if has tshark;   then manifest_add tshark   tshark   reverse global apt        "tshark --version" core "CLI packet analysis (Wireshark GUI: Windows)"; fi
    if has 7z;       then manifest_add p7zip    7z       reverse global apt        "command -v 7z"       core "archive inspection/extraction"; fi
    if has foremost; then manifest_add foremost foremost reverse global apt        "command -v foremost" core "file carving from raw data"; fi
    if has xxd;      then manifest_add xxd      xxd      reverse global apt        "command -v xxd"      core "hex viewer/editor"; fi
    if has hexdump;  then manifest_add hexdump  hexdump  reverse global apt        "command -v hexdump"  core "hex dump (bsdextrautils)"; fi
    if has file;     then manifest_add file     file     reverse global apt        "file --version"   core "file-type identification"; fi
    if has dosbox-x; then manifest_add dosbox-x dosbox-x reverse global apt        "command -v dosbox-x" core "DOS emulator; run headless via dosbox-x-headless"; fi
    if has frida;    then manifest_add frida    frida    reverse global pipx       "frida --version"  core "dynamic instrumentation"; fi
    if [ -e "$HOME/tools/bin/ghidra" ]; then manifest_add ghidra ghidra reverse global github-zip "command -v ghidra" core "NSA RE suite; GUI via 'ghidra', headless via 'ghidra-headless'"; fi
    log_ok "manifest updated — reverse group"
}
